import subprocess
import json
import re
import difflib
import concurrent.futures
from pathlib import Path
from typing import List, Dict
from dataclasses import dataclass

# ======================= CONFIGURATION =======================
INPUT_FILE = Path("spotify_playlists_backup.txt")
OUTPUT_FILE = Path("urls_production.txt")
CACHE_FILE = Path("youtube_cache_prod.json")
MAX_WORKERS = 4 
YT_SEARCH_LIMIT = 5
MIN_CONFIDENCE_SCORE = 50 
# =============================================================

@dataclass
class Track:
    number: str
    title: str
    artist: str
    album: str
    raw_line: str

    @property
    def search_query(self) -> str:
        # Search specifically for audio first to minimize "Music Video" intro noise
        clean_artist = self.artist.split("feat.")[0].strip()
        return f"{self.title} {clean_artist} official audio"

@dataclass
class VideoResult:
    id: str
    title: str
    channel: str
    duration: int # in seconds
    url: str
    is_topic: bool = False # Flag for auto-generated channels

class PlaylistArchitect:
    def __init__(self):
        self.cache = self._load_cache()
        self.line_pattern = re.compile(
            r"^(\d+)\.\s+(.+?)\s+[—\-]\s+(.+?)(?:\s+\[(.*?)\])?\s*\(spotify:track:"
        )

    def _load_cache(self) -> Dict[str, str]:
        if CACHE_FILE.exists():
            try:
                return json.loads(CACHE_FILE.read_text(encoding="utf-8"))
            except Exception:
                return {}
        return {}

    def _save_cache(self):
        CACHE_FILE.write_text(json.dumps(self.cache, indent=2), encoding="utf-8")

    def parse_file(self, file_path: Path) -> Dict[str, List[Track]]:
        if not file_path.exists():
            return {}
        content = file_path.read_text(encoding="utf-8")
        content = re.sub(r'\\"+', '', content)
        lines = content.splitlines()
        playlists = {}
        current_playlist_name = "Unknown"
        current_tracks = []

        for line in lines:
            line = line.strip()
            if not line: continue
            if line.startswith("Playlist:"):
                if current_tracks: playlists[current_playlist_name] = current_tracks
                current_playlist_name = line.replace("Playlist:", "").strip()
                current_tracks = []
                continue
            if line.startswith("ID:") or "Tracks expected:" in line: continue

            match = self.line_pattern.match(line)
            if match:
                artist_raw = match.group(3).strip()
                primary_artist = artist_raw.split(",")[0].strip() # Take primary
                track = Track(
                    number=match.group(1),
                    title=match.group(2).strip(),
                    artist=primary_artist,
                    album=match.group(4).strip() if match.group(4) else "",
                    raw_line=line
                )
                current_tracks.append(track)
        
        if current_tracks: playlists[current_playlist_name] = current_tracks
        return playlists

    def get_similarity(self, s1: str, s2: str) -> float:
        return difflib.SequenceMatcher(None, s1.lower(), s2.lower()).ratio()

    def advanced_scoring(self, track: Track, video: VideoResult) -> int:
        """
        Production-Grade Heuristic Engine
        """
        score = 0
        
        # Normalization
        vid_title_norm = video.title.lower()
        vid_channel_norm = video.channel.lower()
        target_title_norm = track.title.lower()
        target_artist_norm = track.artist.lower()

        # ---------------------------------------------------------
        # 1. THE "WHO" (Channel Trust)
        # ---------------------------------------------------------
        # "Topic" channels are auto-generated by YouTube from the record label.
        # They are ALWAYS the song, no video, exact length. Highest Trust.
        if "topic" in vid_channel_norm and target_artist_norm in vid_channel_norm:
             score += 40
             video.is_topic = True
        elif target_artist_norm in vid_channel_norm or "vevo" in vid_channel_norm:
             score += 25
        
        # ---------------------------------------------------------
        # 2. THE "WHAT" (Semantic Title Match)
        # ---------------------------------------------------------
        # Exact title match is huge.
        if target_title_norm == vid_title_norm:
            score += 30
        elif target_title_norm in vid_title_norm:
            score += 20
        else:
            # Fuzzy match for slight variations
            sim = self.get_similarity(target_title_norm, vid_title_norm)
            if sim > 0.8: score += 15
            elif sim > 0.6: score += 5
            else: score -= 20 # Title mismatch penalty

        # Asset Type Preference
        if "official audio" in vid_title_norm: score += 10
        elif "official video" in vid_title_norm: score += 5
        elif "lyric" in vid_title_norm: score += 2

        # ---------------------------------------------------------
        # 3. THE "HOW LONG" (Smart Duration Filtering)
        # ---------------------------------------------------------
        # We don't know the exact Spotify duration, but we can assume standard pop/rock 
        # structure (150s - 300s). We rely on relative logic.
        
        # FATAL: If video is suspiciously short (< 90s), it's likely a snippet/TikTok.
        # Unless the song title implies it's an "Intro" or "Interlude".
        is_interlude = any(x in target_title_norm for x in ["intro", "outro", "interlude", "pt. 1"])
        
        if video.duration < 90 and not is_interlude:
            score -= 50 # Massive penalty for shorts
        
        # If it's a "Topic" channel (Audio only), duration should be standard.
        # If it's a "Video", we TOLERATE extra length (intros/outros).
        if video.duration > 600: # > 10 mins
            score -= 20 # Likely a full album or DJ set
        
        # ---------------------------------------------------------
        # 4. THE FILTERS (Negative Keywords)
        # ---------------------------------------------------------
        # We want the original recording, not a reinterpretation.
        bad_words = ["cover", "remix", "live", "concert", "reaction", "review", "tutorial", "lesson", "karaoke", "instrumental", "making of", "parody", "tribute", "demo", "bootleg", "acoustic", "rehearsal"]
        
        for word in bad_words:
            # If the original song title *contains* "Remix" or "Live", we allow it.
            # Otherwise, it's a false positive.
            if word in vid_title_norm and word not in target_title_norm:
                if word == "reaction": score -= 100 # Immediate disqualify
                elif word == "cover": score -= 60
                else: score -= 30

        return score

    def search_youtube(self, track: Track) -> str:
        cache_key = f"{track.title}|{track.artist}"
        if cache_key in self.cache: return self.cache[cache_key]

        # Search Query Strategy:
        # We add "official audio" to the search query.
        # This biases YouTube's algorithm to show the static image version first (Audio),
        # rather than the Music Video (which might have intros).
        query = f"{track.title} {track.artist} official audio"
        
        cmd = ["yt-dlp", "--dump-json", "--flat-playlist", "--no-warnings", f"ytsearch{YT_SEARCH_LIMIT}:{query}"]

        try:
            # Run search
            result = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="ignore")
            
            candidates = []
            for line in result.stdout.splitlines():
                try:
                    d = json.loads(line)
                    candidates.append(VideoResult(
                        id=d.get("id"),
                        title=d.get("title", ""),
                        channel=(d.get("channel") or d.get("uploader") or ""),
                        duration=d.get("duration", 0) or 0,
                        url=d.get("webpage_url") or f"https://www.youtube.com/watch?v={d.get('id')}"
                    ))
                except: pass
            
            if not candidates: return "NO_MATCH"

            # Score candidates
            best_v = None
            best_s = -1000

            for v in candidates:
                s = self.advanced_scoring(track, v)
                if s > best_s:
                    best_s = s
                    best_v = v
            
            # Final Decision
            if best_s >= MIN_CONFIDENCE_SCORE:
                self.cache[cache_key] = best_v.url
                return best_v.url
            else:
                print(f"    ⚠️ Low Confidence: {track.title} (Best Score: {best_s})")
                return "NO_MATCH"

        except Exception as e:
            print(f"    ❌ Error searching {track.title}: {e}")
            return "ERROR"

    def process(self):
        print("🏗️  Initializing Playlist Architect...")
        data = self.parse_file(INPUT_FILE)
        
        with OUTPUT_FILE.open("w", encoding="utf-8") as f:
            for pl_name, tracks in data.items():
                f.write(f"Playlist: {pl_name}\n")
                print(f"\n📂 Playlist: {pl_name} ({len(tracks)} tracks)")
                
                results = [None] * len(tracks)
                
                # Parallel Processing
                with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
                    futures = {executor.submit(self.search_youtube, t): i for i, t in enumerate(tracks)}
                    
                    for future in concurrent.futures.as_completed(futures):
                        idx = futures[future]
                        track = tracks[idx]
                        try:
                            url = future.result()
                            results[idx] = url
                            if "youtube" in url:
                                print(f"   ✅ {track.title} -> Found")
                            else:
                                print(f"   ❌ {track.title} -> Not Found")
                        except:
                            results[idx] = "ERROR"

                for url in results:
                    f.write(f"{url}\n")
                f.write("\n" + "-"*40 + "\n\n")
                self._save_cache()

if __name__ == "__main__":
    bot = PlaylistArchitect()
    bot.process()